### ISSUE TITLE
Signs with limiting subsign

### ISSUE THREAD

**Issue by flohoff** [yopaseopor/traffic_signs_style_JOSM#12]
Hi,

I am lost how to Tag DE:251;DE1020-30 - motorcar=destination. It seems the view does not like it.

Both individually get shown - Tagging them both doesnt.

Flo

**Comment by yopaseopor** [comment]
It is normal, the reason is MAPCSS does not allow to show two icons at the same node. For this reason you can see every icon when you put it separately.
Also I recommend to tag traffic signs as a subtag with unique value like:

traffic_sign:forward=DE:251
traffic_sign:2:forward=DE:1020-30
side=right

You can try the preset traffic_signs_DE

**Comment by flohoff** [comment]
But this is "broken" - It encourages people to seperate signs which are together and contradicts the tagging as mentioned in the Wiki.

I was trying to find the corresponding Josm tickets concerning multiple icons and found this:

https://josm.openstreetmap.de/ticket/14098

Flo

**Comment by yopaseopor** [comment]
Fixed. Thank you very much for the information to fix the issue. Now the styles recognise and show you on the same node the two traffic signs
![clipboard01](https://user-images.githubusercontent.com/5250646/40750615-27cc7c9c-6468-11e8-97d9-ec679731b1b6.jpg)
